name: Docker Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app:latest .
      working-directory: rest-service3

    - name: Test Docker image
      run: docker run --rm my-app:latest java -version
